### ISSUE TITLE
Add the paper "Attending to Discriminative Certainty for Domain Adaptation"

### ISSUE THREAD

**Issue by Sshanu** [zhaoxin94/awsome-domain-adaptation#11]
Hi,

Please, add the paper  [Attending to Discriminative Certainty for Domain Adaptation](http://openaccess.thecvf.com/content_CVPR_2019/papers/Kurmi_Attending_to_Discriminative_Certainty_for_Domain_Adaptation_CVPR_2019_paper.pdf) which is accepted in CVPR 2019. 

Thanks,
Shanu

**Comment by Sshanu** [comment]
Also, the paper [Adversarial Adaptation of Scene Graph Models for Understanding Civic Issues
](https://dl.acm.org/citation.cfm?id=3313681), which is accepted in The Web Conference 2019. This paper is about the adaptation of scene graphs.

**Comment by zhaoxin94** [comment]
Ok, I have added the two papers to the list.

**Comment by Sshanu** [comment]
Thanks
