### ISSUE TITLE
Please add an related paper on Domain Adaptation via Disentangled Representations

### ISSUE THREAD

**Issue by Junlin639** [zhaoxin94/awsome-domain-adaptation#8]
Hi,

Could you please add our new work into this list? The paper is about Unsupervised Domain Adaptation via Disentangled Representations. 

You could find the paper here: https://arxiv.org/abs/1907.13590

Thank you!

Best,
Junlin

**Comment by zhaoxin94** [comment]
OK! I have put your paper in the medical-related section.
